version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    dependencies:
      patterns:
      - "*"
      exclude-patterns:
      - "rand*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
