language: rust
cache:
  directories:
    - "$HOME/.cargo"
    - "$HOME/bin"
# hopefully prevent the cache from becoming huge - https://levans.fr/rust_travis_cache.html
before_cache:
  - rm -rf /home/travis/.cargo/registry
rust:
  - 1.41.0
branches:
  only:
    - master
    - sync-async-api
before_install:
  # key for integration tests
  - openssl aes-256-cbc -K $encrypted_d5683c11b5e1_key -iv $encrypted_d5683c11b5e1_iv -in tests/testkeys/iak-dev.pem.enc -out tests/testkeys/iak-dev.pem -d
before_script:
  - rustup component add rustfmt-preview
  - cross --version || cargo install cross
matrix:
  include:
    # Linux
    - name: Travis Default Environment (Ubuntu Linux)
      os: linux
    # OSX
    - name: OSX x86_64
      os: osx
    # iOS
    - name: iOS x64
      os: osx
      env:
        - TARGET=aarch64-apple-ios
        - IOS=1
    # Android
# Disabling until we have better proto support. See https://github.com/IronCoreLabs/ironoxide/pull/27
#    - name: Android x64
#      os: linux
#      env:
#        - TARGET=aarch64-linux-android
script:
  - "./.travis_scripts/cross-test.sh"
