name: Build

on:
  push:
    branches:
      - master
      - 133-github-actions
  pull_request:

jobs:
  cargo-build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        target:
          [
            aarch64-linux-android,
            armv7-linux-androideabi,
            i686-linux-android,
            x86_64-linux-android,
          ]
        os: [ubuntu-18.04]
        include:
          - target: aarch64-apple-ios
            os: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Generate Cargo.lock so we can cache from it
        run: cargo generate-lockfile
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.workflow }}-rust-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.workflow }}-rust-${{ matrix.target }}-
      - uses: actions-rs/cargo@v1
        with:
          # `cross` won't work on aarch64-apple-ios, so it falls back to `cargo` in that case
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --features "beta blocking tls-rustls" --no-default-features
