name: Daily runs

# Run daily and also when Cargo.toml changes
on:
  schedule:
    - cron: "0 8 * * *" # 8AM UTC
  push:
    branches:
      - daily-test-hack-day
    # paths:
    #   - "**/Cargo.toml"
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run audit checker
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt test keys
        run: openssl aes-256-cbc -d -K ${{ secrets.OPENSSL_KEY }} -iv ${{ secrets.OPENSSL_IV }} -in tests/testkeys/iak-dev.pem.enc -out tests/testkeys/iak-dev.pem
      # - run: cargo test --all-features
      - run: exit 1
      - name: Post to Slack
        if: failure()
        run: |
          curl -L -X POST '${{ secrets.SLACK_WEBHOOK }}' \
          -F 'payload="{\"text\": \"Failed a run of <${{env.GITHUB_SERVER_URL}}/${{env.GITHUB_REPOSITORY}}/actions/runs/${{env.GITHUB_RUN_ID}}|${{env.GITHUB_REPOSITORY}}>.\"}"'
