name: Daily runs

on:
  schedule:
    - cron: "0 14 * * *" # Daily at 2pm UTC

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Generate the Cargo.lock that will be used for the tests so we can upload it as an artifact
      - run: cargo generate-lockfile
      - uses: actions/upload-artifact@v3
        with:
          path: Cargo.lock
      - name: Decrypt test keys
        uses: IronCoreLabs/ironhide-actions/decrypt@v2
        with:
          keys: ${{ secrets.IRONHIDE_KEYS }}
          input: tests/testkeys/iak-stage.pem.iron
      - run: cargo test --features beta
        env:
          IRONCORE_ENV: stage
